package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.DockerCommandStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Identity_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Identity_Build")) {
    expectSteps {
        maven {
            goals = "clean package"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
            jdkHome = "%env.JDK_11%"
        }
        script {
            name = "Add sumo_credentials.txt"
            scriptContent = "cp /home/sumo_credentials.txt ./"
        }
        dockerCommand {
            commandType = build {
                source = file {
                    path = "Dockerfile"
                }
                namesAndTags = "artemkulish/demo4:identity"
            }
            param("dockerImage.platform", "linux")
        }
        dockerCommand {
            commandType = push {
                namesAndTags = "artemkulish/demo4:identity"
            }
            param("dockerfile.path", "Dockerfile")
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            name = "Starter Build"
            goals = "mvn clean install"
            pomLocation = "./identity-starter/pom.xml"
            runnerArgs = ""
            localRepoScope = MavenBuildStep.RepositoryScope.AGENT
            jdkHome = ""
        }
        update<ScriptBuildStep>(1) {
            name = "Identity Build"
            scriptContent = """
                cd ./identity-service/pom.xml
                sudo mvn clean package
            """.trimIndent()
        }
        insert(2) {
            script {
                name = "Add sumo_credentials.txt"
                scriptContent = "cp /home/sumo_credentials.txt ./"
            }
        }
        insert(3) {
            script {
                name = "Docker Build"
                scriptContent = """
                    cd ./identity-service/
                    sudo docker build -t artemkulish/demo4:identity .
                """.trimIndent()
            }
        }
        update<DockerCommandStep>(4) {
            name = "Docker Push"
            commandType = push {
                namesAndTags = "artemkulish/demo4:identity"
                removeImageAfterPush = true
            }
            param("dockerImage.platform", "")
            param("dockerfile.path", "")
        }
        items.removeAt(5)
    }
}
