package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Identity_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Identity_Build")) {
    expectSteps {
        maven {
            goals = "clean package"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
            jdkHome = "%env.JDK_11%"
        }
        script {
            name = "Add sumo_credentials.txt"
            scriptContent = "cp /home/sumo_credentials.txt ./"
        }
        dockerCommand {
            commandType = build {
                source = file {
                    path = "Dockerfile"
                }
                namesAndTags = "artemkulish/demo4:identity"
            }
            param("dockerImage.platform", "linux")
        }
        dockerCommand {
            commandType = push {
                namesAndTags = "artemkulish/demo4:identity"
            }
            param("dockerfile.path", "Dockerfile")
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            goals = "clean install"
            pomLocation = "./identity-starter/pom.xml"
        }
        insert(1) {
            maven {
                goals = "clean package"
                pomLocation = "./identity-service/pom.xml"
                jdkHome = "%env.JDK_11%"
            }
        }
    }
}
