package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Identity_Database_Update'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Identity_Database_Update")) {
    expectSteps {
        script {
            name = "Identity_Database_Update"
            executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
            scriptContent = """
                cd ./identity_service/
                sudo mvn liquibase:update
            """.trimIndent()
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            scriptContent = "cd ./identity_service/ && sudo mvn liquibase:update"
        }
    }
}
