package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Trip_Test'
in the project with id = 'Trip', and delete the patch script.
*/
create(RelativeId("Trip"), BuildType({
    id("Trip_Test")
    name = "Test"

    vcs {
        root(RelativeId("Trip_HttpsGithubComDevOpsDp185TestsGitRefsHeadsMaster"))
    }

    triggers {
        vcs {
        }
    }
}))

