package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Payment'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Payment")) {
    expectBuildTypesOrder()
    buildTypesOrderIds = arrayListOf(RelativeId("Payment_Build"), RelativeId("Payment_Deploy"), RelativeId("Payment_Database_Update"), RelativeId("Payment_Database_Rollback"))
}
