package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Trip_HttpsGithubComDevOpsDp185TestsGitRefsHeadsMaster'
in the project with id = 'Trip', and delete the patch script.
*/
create(RelativeId("Trip"), GitVcsRoot({
    id("Trip_HttpsGithubComDevOpsDp185TestsGitRefsHeadsMaster")
    name = "https://github.com/DevOps-DP-185/Tests.git#refs/heads/master"
    url = "https://github.com/DevOps-DP-185/Tests.git"
    authMethod = password {
        userName = "ArtemKulish"
        password = "credentialsJSON:91a788d6-72b3-405f-a9df-03389f20d48c"
    }
}))

