version: '3.1'

services:

  zookeeper:
    image: zookeeper:latest
    ports:
      - 2181:2181
     
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092    
    env_file:
      - ./env/kafka.env

  gateway:
    image: artemkulish/demo4:gateway
    depends_on:
      - kafka
    ports:
      - 80:8080
    env_file:
      - ./env/gateway.env

  discovery:
    image: artemkulish/demo4:discovery
    depends_on:
      - kafka
    ports:
      - 8761:8761
         
  messaging:
    image: artemkulish/demo4:messaging
    depends_on:
      - kafka
    ports:
      - 8084:8080
    env_file:
      - ./env/messaging.env  
      
  identity:
    image: artemkulish/demo4:identity
    ports:
      - 8085:8080
    env_file:
      - ./env/identity.env
      
  payment:
    image: artemkulish/demo4:payment
    ports:
      - 8083:8080
    env_file:
      - ./env/payment.env
      
  trip:
    image: artemkulish/demo4:trip
    depends_on:
      - kafka
    ports:
      - 8086:8080
    env_file:
      - ./env/trip.env 

  vehicle:
    image: artemkulish/demo4:vehicle
    depends_on:
      - kafka
    ports:
      - 8081:8080
    env_file:
      - ./env/vehicle.env

  simulator:
    image: artemkulish/demo4:simulator
    depends_on:
      - kafka
      - vehicle
    ports:
      - 8088:8080
    env_file:
      - ./env/simulator.env    
